import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import { defaultLocale, locales, messages, type Locale } from "./i18n";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const cookieStore = cookies();
  const localeCookie = cookieStore.get("LOCALE")?.value as Locale | undefined;
  const locale = locales.includes(localeCookie as any) ? (localeCookie as Locale) : defaultLocale;
  const t = messages[locale];

  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="border-b">
          <div className="mx-auto max-w-6xl px-6 py-3 flex items-center justify-between text-sm">
            <div className="flex items-center gap-4">
              <a href="/">MyPlatform</a>
              <a href="/pricing">{t.pricing}</a>
              <a href="/get-started" className="rounded bg-black px-3 py-1 text-white">{t.getStarted}</a>
            </div>
            <form action="/locale" method="post">
              <select name="locale" defaultValue={locale} className="rounded border p-1">
                {locales.map((l) => (
                  <option key={l} value={l}>{l}</option>
                ))}
              </select>
            </form>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
